### ISSUE TITLE
Q: Can we use multiple Limiters on a single app?

### ISSUE THREAD

**Issue by Lalbatros** [alisaifee/flask-limiter#269]
Hi alisaifee,

I am trying to apply two sets of default limits on all routes, by using this code:

```
limiter = Limiter(app,
    key_func=get_remote_address,
    default_limits=["30 / minute", "500 / hour", "2000 / day"],
    headers_enabled=True,
    storage_uri=LIMITER_URI,
    in_memory_fallback_enabled=True
)
global_limiter = Limiter(
    app,
    key_func=lambda:"global_bucket",
    default_limits=["100 / minute"],
    headers_enabled=True,
    storage_uri=LIMITER_URI,
    in_memory_fallback_enabled=True
)
```
This behaves differently than using `global_limiter = limiter.shared_limit("100/minute", scope=lambda:"global_bucket")` because this way, I wouldn't have to mention `@global_limiter`before all routes.

However it appears global_limiter is not applied.

Besides, I could not find any example of people using multiple Limiters on any app. Would you have an idea of how to accomplish this?

**Comment by wbobeirne** [comment]
I'm running into a use case for this as well. I want to provide limits on a per-user level, but also a per-user group level (this lets me set higher per-user limits, so if a single user has a burst of activity it's OK but not if all of the users in a group are all bursting at the same time.)

Even with two separate limiters and separate decorators, I'm finding that the second decorator doesn't trigger. I haven't dug too deep, but I'm seeing some setting and checking of `g._rate_limiting_complete` which would be contaminated across multiple instances of flask_limiter, and may cause the second limiter to get skipped over.

**Comment by alisaifee** [comment]
I think this is resolved by #286. Please re-open if that is not the case.

**Comment by salmanrk** [comment]
I have tried #286 and added a key_prefix to each. However, that didn't solve the problem. 
Any solutions?

**Comment by alisaifee** [comment]
Could you provide an example that shows what the issue is?

**Comment by alisaifee** [comment]
Here's an example test case that demonstrates using multiple limiter extensions on the same app: https://github.com/alisaifee/flask-limiter/blob/master/tests/test_flask_ext.py#L721

**Comment by alisaifee** [comment]
I think I hadn't read the description of the issue correctly. There was still an existing gap where default limits (and generally any actions the extension took in before/after request hooks, were not being registered once *an* instance of flask-limiter was registered on an application).

**Comment by salmanrk** [comment]
> I think I hadn't read the description of the issue correctly. There was still an existing gap where default limits (and generally any actions the extension took in before/after request hooks, were not being registered once _an_ instance of flask-limiter was registered on an application).

Dear Ali,

I apologize for not providing the code initially. However I did try the example you provided. And it turns out I had to set limiter2 under the route in order for it to work. (originally I was doing everything same as the example except for setting limiter2 under the route)
Initially I didn't specify them under routes I thought it should apply on all by default. 
limiter1 is by default working on all. But limiter2 had to be specified under the route. 
I tested them with filters on both as well and they are working properly. 
Great module!

**Comment by alisaifee** [comment]
I've released [2.5.0](https://github.com/alisaifee/flask-limiter/releases/tag/2.5.0) which contains a fix to allow multiple extension instances to correctly register the before/after hooks so that default limits from multiple extensions all get applied on the routes. 

If you can give that version a shot to see if that resolves the issue I'd appreciate it!

**Comment by salmanrk** [comment]
I upgraded to 2.5.0 and initiated limiter1 and limiter2 without applying them directly under any route.
I can confirm that both are working correctly as default limits. Great job!! 
``

**Comment by alisaifee** [comment]
Thanks for verifying!
